### PR TITLE
Multiple fixes & new native

### PR DESCRIPTION
**Pull request by AgentWesker**

### CODE REVIEW

**Comment by LubricantJam** [comment]
Thank you for your contribution, I've tested this on my servers and works well. All good for merging.

**Comment by Cruze03** [comment]
@AgentWesker Did you test this?

**Comment by AgentWesker** [comment]
I just tested it today and it seems to work fine so far

**Comment by AgentWesker** [comment]
Might want to post the new convar somewhere in case you decide to merge so they know to use it

**Comment by AgentWesker** [comment]
Added a few more security enhancements since last comment

**Comment by Cruze03** [comment]
Thanks <3

**Pull request merged**
