### PR TITLE
[FIX] RU translations

### PR DESCRIPTION
**Pull request by Classes123**
"Discord" means strife :)

and other funny words.

### CODE REVIEW

**Comment by valeologist** [comment]
https://github.com/Cruze03/discord-utilities/pull/7

**Comment by Classes123** [comment]
You didn't fix them fully

**Comment by Cruze03** [comment]
Can you update with the latest translation file? Thanks!

**Comment by Blueberryy** [comment]
You can close your pull request. I added your fixes on my pull

**Pull request closed without merging**
