### PR TITLE
Update discord_utilities.sp

### PR DESCRIPTION
**Pull request by xSL0W**
```
L 08/29/2020 - 08:39:48: [SM] Exception reported: Not enough space on the heap
L 08/29/2020 - 08:39:48: [SM] Blaming: discord_utilities.smx
L 08/29/2020 - 08:39:48: [SM] Call stack trace:
L 08/29/2020 - 08:39:48: [SM]   [0] SteamWorks_GetHTTPResponseBodyCallback
L 08/29/2020 - 08:39:48: [SM]   [1] Line 86, C:\Users\xSLOW\Desktop\compilerV2\include\discord_utilities/helpers.sp::MembersDataReceive
```

Fixing space on heap on discord_utilities.sp too

### CODE REVIEW

**Comment by xSL0W** [comment]
after setting the #pragma dynamic to 100000 (now became 400k after compile) it works great for my big ass server
(1350 members, 100 channels)

**Comment by Cruze03** [comment]
I just need this plugin to support at least 5000 members as of now. What do you think will be a suitable value?

And discord api doesn't need that much of a value coz no-one would be having 1000 channels lol

**Comment by alexevladgabriel** [comment]
It seems that **#pragma dynamic 25000**, worked for **LubricantJam** discord (**5000+ members**), but he got another error on plugin loading from **discord_api**.

**Comment by xSL0W** [comment]
When you get members through that function what else do you get?
Its weird if it works on his discord server and on mine doesnt work without increasing it.

**Comment by LubricantJam** [comment]
I don't think it worked at all, just another error occured.

**Comment by xSL0W** [comment]
`L 08/30/2020 - 15:31:12: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "discord_utilities.smx")
L 08/30/2020 - 15:31:12: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "discord_utilities.smx")
L 08/30/2020 - 15:31:12: [SM] Unloading plugin to free 32397 handles.
L 08/30/2020 - 15:31:12: [SM] Unloading plugin to free 32397 handles.
L 08/30/2020 - 15:31:12: [SM] Contact the author(s) of this plugin to correct this error.
L 08/30/2020 - 15:31:12: [SM] Contact the author(s) of this plugin to correct this error.
L 08/30/2020 - 15:31:12: --------------------------------------------------------------------------
L 08/30/2020 - 15:31:12: --------------------------------------------------------------------------
L 08/30/2020 - 15:31:12: Type   IDatabase           |   Count   3
L 08/30/2020 - 15:31:12: Type   IDatabase           |   Count   3
L 08/30/2020 - 15:31:12: Type   Timer               |   Count   1
L 08/30/2020 - 15:31:12: Type   Timer               |   Count   1
L 08/30/2020 - 15:31:12: Type   GlobalFwd           |   Count   3
L 08/30/2020 - 15:31:12: Type   GlobalFwd           |   Count   3
L 08/30/2020 - 15:31:12: Type   Trie                |   Count   3
L 08/30/2020 - 15:31:12: Type   Trie                |   Count   3
L 08/30/2020 - 15:31:12: Type   HTTPHandle          |   Count   1
L 08/30/2020 - 15:31:12: Type   HTTPHandle          |   Count   1
L 08/30/2020 - 15:31:12: Type   JanssonObject       |   Count   32386
L 08/30/2020 - 15:31:12: Type   JanssonObject       |   Count   32386
L 08/30/2020 - 15:31:12: -- Approximately 1172 bytes of memory are in use by (32397) Handles.

L 08/30/2020 - 15:31:12: -- Approximately 1172 bytes of memory are in use by (32397) Handles.

L 08/30/2020 - 15:31:12: [SM] Exception reported: Memory leak
L 08/30/2020 - 15:31:12: [SM] Blaming: discord_api.smx
L 08/30/2020 - 15:31:12: [SM] Call stack trace:
L 08/30/2020 - 15:31:12: [SM]   [0] json_object_get
L 08/30/2020 - 15:31:12: [SM]   [1] Line 18, C:\Users\xSLOW\Desktop\compilerV2\include\discord/stocks.inc::JsonObjectGetString
L 08/30/2020 - 15:31:12: [SM]   [2] Line 4, C:\Users\xSLOW\Desktop\compilerV2\include\discord/UserObject.sp::Native_DiscordUser_GetID
L 08/30/2020 - 15:31:12: [SM]   [4] DiscordUser.GetID
L 08/30/2020 - 15:31:12: [SM]   [5] Line 140, C:\Users\xSLOW\Desktop\compilerV2\include\discord_utilities/helpers.sp::OnGetMembersAll
L 08/30/2020 - 15:31:12: [SM]   [6] Line 94, C:\Users\xSLOW\Desktop\compilerV2\include\discord_utilities/helpers.sp::GetMembersData
L 08/30/2020 - 15:31:12: [SM]   [8] SteamWorks_GetHTTPResponseBodyCallback
L 08/30/2020 - 15:31:12: [SM]   [9] Line 86, C:\Users\xSLOW\Desktop\compilerV2\include\discord_utilities/helpers.sp::MembersDataReceive
L 08/30/2020 - 15:31:12: [SM] Exception reported: Could not create <Object> handle.
L 08/30/2020 - 15:31:12: [SM] Blaming: discord_api.smx
L 08/30/2020 - 15:31:12: [SM] Call stack trace:
L 08/30/2020 - 15:31:12: [SM]   [0] json_object_get
L 08/30/2020 - 15:31:12: [SM]   [1] Line 18, C:\Users\xSLOW\Desktop\compilerV2\include\discord/stocks.inc::JsonObjectGetString
L 08/30/2020 - 15:31:12: [SM]   [2] Line 4, C:\Users\xSLOW\Desktop\compilerV2\include\discord/UserObject.sp::Native_DiscordUser_GetID
L 08/30/2020 - 15:31:12: [SM]   [4] DiscordUser.GetID
L 08/30/2020 - 15:31:12: [SM]   [5] Line 140, C:\Users\xSLOW\Desktop\compilerV2\include\discord_utilities/helpers.sp::OnGetMembersAll
L 08/30/2020 - 15:31:12: [SM]   [6] Line 94, C:\Users\xSLOW\Desktop\compilerV2\include\discord_utilities/helpers.sp::GetMembersData
L 08/30/2020 - 15:31:12: [SM]   [8] SteamWorks_GetHTTPResponseBodyCallback
L 08/30/2020 - 15:31:12: [SM]   [9] Line 86, C:\Users\xSLOW\Desktop\compilerV2\include\discord_utilities/helpers.sp::MembersDataReceive
`

it works now, but im getting mem leaks.

**Pull request closed without merging**
